spring.application.name=S46L03-AuthController_Add_Validations

# Server port
server.port=8080

# Database config
spring.datasource.url=jdbc:h2:file:./db/db
spring.datasource.username=admin
spring.datasource.password=pass987

# setup local h2 database console
spring.h2.console.enabled=true
spring.h2.console.path=/db-console
spring.h2.console.settings.web-allow-others=false

# local h2 tables setup on startup, use the value 'none' in production
spring.jpa.hibernate.ddl-auto=create

# Logging settings
logging.level.org.maharnur.prathamesh=DEBUG
logging.pattern.console=%d [%level] %c{1} [%t] %m%n
logging.file.name=appLog.log
logging.pattern.file=%d [%level] %c{1} [%t] %m%n


